### ISSUE TITLE
Target Workload AWS account required InfraBuildRole and CloudOps?

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws-multi-region-cicd-with-terraform#4]
Hihi! 

Had been reading through the walkthrough but i missed out if the workload accounts needs to have the IAM Role InfraBuildRole as a prerequisite?

Thanks for reading

**Comment by lernae** [comment]
Hi @ahkai86 

For the sample, InfraBuildRole is required in the target workload account.  Details are at [Prerequisite](https://github.com/aws-samples/aws-multi-region-cicd-with-terraform#prerequisite) under [Sample infra workload](https://github.com/aws-samples/aws-multi-region-cicd-with-terraform#sample-infra-workload) with further details in the [script](https://github.com/aws-samples/aws-multi-region-cicd-with-terraform/blob/main/scripts/prerequisites/create-iam-resources_for_workload_account.sh).

**Comment by ahkai86** [comment]
@lernae , thanks so much for the prompt reply! really appreciated 
Btw does the S3 buckets needs to be created prior to the terraform apply in Step 1: Prerequisites?

**Comment by lernae** [comment]
The S3 buckets per environment needs to be created as per the [Terraform remote state management](https://github.com/aws-samples/aws-multi-region-cicd-with-terraform#terraform-remote-state-management) bullet under "Create S3 buckets per environment with name ...". The approach shown within the sub-bullets under "Create S3 buckets per environment with name ..." bullet is an example of how to do that using Terraform.  If the Terraform approach of creating S3 buckets described in the sub-bullets is followed then the terraform apply would create the S3 buckets.
