### ISSUE TITLE
Change type of account variable

### ISSUE THREAD

**Issue by anhpnv** [aws-samples/aws-multi-region-cicd-with-terraform#8]
**What happened:**
 Because type of account is int so if my account number is "0123456", it will delete my "0" and output is "123456", and this is wrong output
**My solution:**
 I want to change "type = string" in variable account
<img width="395" alt="image" src="https://github.com/aws-samples/aws-multi-region-cicd-with-terraform/assets/40441000/275b17f2-a607-45c4-8424-854180d6cfef">

Can i push a pull request 🙏🙏

**Comment by lernae** [comment]
Thanks for reporting this @anhpnv!  Yes, please share a PR on it.

**Comment by lernae** [comment]
Thank you @anhpnv
